import Icon from '../common/Icons.jsx';

export default function ChatInfoModal({ conversation, onClose, onClear }) {
  return <div role="dialog" aria-modal="true" aria-label="Söhbət Məlumatları" className="fixed inset-0 z-50 flex bg-slate-900/60 backdrop-blur-sm items-center justify-center p-4"><div className="bg-white dark:bg-slate-900 rounded-3xl max-w-md w-full p-6 shadow-2xl border border-slate-100 dark:border-slate-800 animate-modal space-y-4">
    <div className="flex items-center justify-between pb-3 border-b border-slate-100 dark:border-slate-800"><h3 className="text-base font-bold text-slate-900 dark:text-white">Söhbət Məlumatları</h3><button onClick={onClose} title="Bağla" className="text-slate-400 hover:text-slate-600"><Icon name="close" className="w-5 h-5" /></button></div>
    <div className="flex flex-col items-center text-center space-y-2"><div className="w-16 h-16 rounded-2xl bg-gradient-to-tr from-brand-600 to-indigo-600 text-white font-bold text-xl flex items-center justify-center shadow-lg">{conversation.type === 'group' ? 'G' : conversation.name.charAt(0)}</div><h4 className="text-base font-black text-slate-900 dark:text-white">{conversation.name}</h4><p className="text-xs text-slate-500">{conversation.type === 'group' ? `Qrup Söhbəti • ${conversation.members.length} iştirakçı` : 'Şəxsi Söhbət'}</p></div>
    <div className="space-y-2 text-xs"><label className="font-bold text-slate-400 uppercase text-[10px]">İştirakçılar</label><div className="space-y-1 max-h-40 overflow-y-auto pr-1">{(conversation.members || [conversation.name, 'Siz']).map(member => <div key={member} className="flex items-center justify-between p-2 rounded-xl bg-slate-50 dark:bg-slate-800 text-xs"><div className="flex items-center gap-2"><span className="w-6 h-6 rounded-full bg-brand-500 text-white font-bold flex items-center justify-center text-[10px]">{member.charAt(0)}</span><span className="font-semibold text-slate-800 dark:text-slate-200">{member}</span></div><span className="w-2 h-2 rounded-full bg-emerald-500" /></div>)}</div></div>
    <div className="pt-3 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between gap-2"><button onClick={onClear} className="px-3.5 py-2 text-xs font-semibold text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-950/40 rounded-xl transition">Mesajları Təmizlə</button><button onClick={onClose} className="px-4 py-2 text-xs font-bold text-white bg-slate-800 hover:bg-slate-700 dark:bg-slate-700 rounded-xl">Bağla</button></div>
  </div></div>;
}
