import { useState } from 'react';
import Icon from '../common/Icons.jsx';

export default function CreateTaskModal({ defaults = {}, onClose, onSave }) {
  const [title, setTitle] = useState(defaults.title || '');
  const [comment, setComment] = useState(defaults.comment || '');
  const [date, setDate] = useState(defaults.date || '2026-09-25');
  const [time, setTime] = useState('12:00');
  const [assignee, setAssignee] = useState('Emil Xanciqazov');
  const [equipment, setEquipment] = useState('Optik Tester və Kabel');
  return <div role="dialog" aria-modal="true" aria-label="Tapşırıq Əlavə Et" className="fixed inset-0 z-50 flex bg-slate-900/60 backdrop-blur-sm items-center justify-center p-4"><div className="bg-white dark:bg-slate-900 rounded-3xl max-w-lg w-full p-6 shadow-2xl border border-slate-100 dark:border-slate-800 animate-modal">
    <div className="flex items-center justify-between pb-3 border-b border-slate-100 dark:border-slate-800"><h3 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2"><span className="p-1.5 rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-950 dark:text-brand-300"><Icon name="tasks" strokeWidth={2.5} /></span>Tapşırıq Əlavə Et (Halal 16)</h3><button onClick={onClose} title="Bağla" className="text-slate-400 hover:text-slate-600"><Icon name="close" className="w-5 h-5" /></button></div>
    <form onSubmit={e => { e.preventDefault(); onSave({ title: title.trim(), comment: comment.trim(), date, time, assignee, equipment }); }} className="space-y-3.5 mt-4 text-xs">
      <div><label htmlFor="task-assignee" className="block font-semibold mb-1 text-slate-700 dark:text-slate-300">İcraçı:</label><select id="task-assignee" required value={assignee} onChange={e => setAssignee(e.target.value)} className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs focus:outline-none focus:ring-2 focus:ring-brand-500">{['Emil Xanciqazov', 'emil xanjiyev', 'İzzət', 'Emil Mahmudov', 'Sayid Mardaliyev', 'Ali Mensimov', 'Vasif Xudiyev'].map(name => <option key={name}>{name}</option>)}</select></div>
      <div><label htmlFor="task-title" className="block font-semibold mb-1 text-slate-700 dark:text-slate-300">Tapşırıq adı:</label><input id="task-title" required value={title} onChange={e => setTitle(e.target.value)} placeholder="Tapşırıq adı" className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs focus:outline-none focus:ring-2 focus:ring-brand-500" /></div>
      <div className="grid grid-cols-2 gap-3"><div><label htmlFor="task-date" className="block font-semibold mb-1 text-slate-700 dark:text-slate-300">Dedlayn (Tarix):</label><input id="task-date" type="date" required value={date} onChange={e => setDate(e.target.value)} className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs focus:outline-none focus:ring-2 focus:ring-brand-500" /></div><div><label htmlFor="task-time" className="block font-semibold mb-1 text-slate-700 dark:text-slate-300">Saat:</label><input id="task-time" type="time" required value={time} onChange={e => setTime(e.target.value)} className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs focus:outline-none focus:ring-2 focus:ring-brand-500" /></div></div>
      <div><label htmlFor="task-equipment" className="block font-semibold mb-1 text-slate-700 dark:text-slate-300">Avadanlıqlar (Halal 16):</label><select id="task-equipment" value={equipment} onChange={e => setEquipment(e.target.value)} className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs focus:outline-none focus:ring-2 focus:ring-brand-500">{['Optik Tester və Kabel', 'Server / Router avadanlığı', 'Laptop və Şəbəkə alətləri', 'Heç biri'].map(item => <option key={item}>{item}</option>)}</select></div>
      <div><label htmlFor="task-comment" className="block font-semibold mb-1 text-slate-700 dark:text-slate-300">Komment / Təsvir:</label><textarea id="task-comment" rows="2" value={comment} onChange={e => setComment(e.target.value)} placeholder="Komment və ya tapşırıq detalları" className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs focus:outline-none focus:ring-2 focus:ring-brand-500 resize-none" /></div>
      <div className="flex items-center justify-end gap-2 pt-3 border-t border-slate-100 dark:border-slate-800"><button type="button" onClick={onClose} className="px-3.5 py-2 text-xs text-slate-500 hover:bg-slate-100 rounded-xl">Ləğv et</button><button type="submit" className="px-5 py-2 text-xs font-bold text-white bg-brand-600 hover:bg-brand-700 rounded-xl shadow">Yadda saxla</button></div>
    </form>
  </div></div>;
}
