import { useState } from 'react';
import Icon from '../common/Icons.jsx';

export default function GroupBulkModal({ users, groups, onClose, onSave }) {
  const [group, setGroup] = useState(groups[0]?.name || '');
  const [members, setMembers] = useState([]);
  return <div role="dialog" aria-modal="true" aria-label="Qrup halında istifadəçi əlavə et" className="fixed inset-0 z-50 flex bg-slate-900/60 backdrop-blur-sm items-center justify-center p-4"><div className="bg-white dark:bg-slate-900 rounded-3xl max-w-md w-full p-6 shadow-2xl border border-slate-100 dark:border-slate-800 animate-modal">
    <div className="flex items-center justify-between pb-3 border-b border-slate-100 dark:border-slate-800"><h3 className="text-base font-bold text-slate-900 dark:text-white">Qrup halında istifadəçi əlavə et</h3><button onClick={onClose} title="Bağla" className="text-slate-400 hover:text-slate-600"><Icon name="close" className="w-5 h-5" /></button></div>
    <div className="space-y-3 mt-4 text-xs"><div><label htmlFor="bulk-target" className="block font-semibold mb-1">Hədəf Qrupu Seçin:</label><select id="bulk-target" value={group} onChange={e => setGroup(e.target.value)} className="w-full px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700">{groups.slice(0, 3).map(item => <option key={item.id} value={item.name}>{item.name}{item.id === 'g2' || item.id === 'g3' ? ' Qrupu' : ''}</option>)}</select></div><div><label className="block font-semibold mb-1">Əlavə ediləcək istifadəçilər:</label><div className="space-y-1.5 max-h-48 overflow-y-auto p-2 bg-slate-50 dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700">{users.map(user => <label key={user.id} className="flex items-center gap-2 p-1.5 hover:bg-white dark:hover:bg-slate-700 rounded-lg cursor-pointer text-xs"><input type="checkbox" checked={members.includes(user.name)} onChange={e => setMembers(e.target.checked ? [...members, user.name] : members.filter(name => name !== user.name))} className="rounded border-slate-300 text-brand-600 focus:ring-brand-500" /><span>{user.name} ({user.company})</span></label>)}</div></div></div>
    <div className="flex items-center justify-end gap-2 mt-6 pt-3 border-t border-slate-100 dark:border-slate-800"><button onClick={onClose} className="px-3.5 py-1.5 text-xs text-slate-500 hover:bg-slate-100 rounded-xl">Ləğv et</button><button onClick={() => onSave(group, members)} className="px-4 py-2 text-xs font-bold text-white bg-emerald-600 hover:bg-emerald-700 rounded-xl shadow">Təsdiq et</button></div>
  </div></div>;
}
