import Icon from '../common/Icons.jsx';

export default function CompaniesView({ companies, onCreate, onEdit }) {
  return <section className="flex-1 flex flex-col h-full bg-slate-50 dark:bg-slate-950 overflow-hidden min-w-0">
    <header className="h-20 px-6 md:px-8 border-b border-slate-200/80 dark:border-slate-800/80 bg-white/95 dark:bg-slate-900/95 backdrop-blur flex items-center justify-between shrink-0 z-10"><div><h1 className="text-xl md:text-2xl font-black tracking-tight text-slate-900 dark:text-white">Şirkətlər Siyahısı</h1><p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">Platformada qeydiyyatdan keçmiş tərəfdaş və müştəri şirkətlər</p></div><button onClick={onCreate} className="px-4 py-2.5 rounded-xl bg-brand-600 hover:bg-brand-700 text-white text-xs font-bold shadow-md shadow-brand-500/25 active:scale-95 transition flex items-center gap-2"><Icon name="plus" strokeWidth={2.5} />Əlavə et (Şirkət Yarat)</button></header>
    <div className="flex-1 overflow-y-auto p-4 md:p-8 space-y-6"><div className="bg-white dark:bg-slate-900 rounded-3xl border border-slate-200/80 dark:border-slate-800 shadow-sm overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left border-collapse min-w-[850px]">
      <thead><tr className="border-b border-slate-100 dark:border-slate-800 bg-slate-50/70 dark:bg-slate-800/40 text-[11px] uppercase tracking-wider font-bold text-slate-400">{['Logo', 'Şirkət adı', 'Ünvan', 'Əlaqə nömrəsi', 'Elektron poçt ünvanı', 'Əməliyyatlar'].map((label, i) => <th key={label} className={`py-3.5 px-4 ${i === 0 ? 'pl-6 w-14' : i === 5 ? 'pr-6 text-right' : ''}`}>{label}</th>)}</tr></thead>
      <tbody className="divide-y divide-slate-100 dark:divide-slate-800/60 text-xs">{companies.map(company => <tr key={company.id} className="hover:bg-slate-50/80 dark:hover:bg-slate-800/40 transition"><td className="py-3.5 pl-6 px-4"><div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-brand-600 to-indigo-600 flex items-center justify-center text-white font-black text-xs shadow-sm">{company.logo}</div></td><td className="py-3.5 px-4 font-bold text-slate-900 dark:text-white">{company.name}</td><td className="py-3.5 px-4 text-slate-600 dark:text-slate-300">{company.address}</td><td className="py-3.5 px-4 font-mono text-[11px] text-slate-600 dark:text-slate-300">{company.phone}</td><td className="py-3.5 px-4 font-mono text-[11px] text-slate-600 dark:text-slate-300">{company.email}</td><td className="py-3.5 pr-6 px-4 text-right"><div className="flex items-center justify-end gap-1.5"><button onClick={() => onEdit(company)} className="p-1.5 text-slate-500 hover:text-brand-600 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg" title="Redaktə et"><svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Z" /></svg></button></div></td></tr>)}</tbody>
    </table></div></div></div>
  </section>;
}
