import Icon from '../common/Icons.jsx';

export default function GroupsView({ groups, onBulk, onNewUser, onChat }) {
  return <section className="flex-1 flex flex-col h-full bg-slate-50 dark:bg-slate-950 overflow-hidden min-w-0">
    <header className="h-20 px-6 md:px-8 border-b border-slate-200/80 dark:border-slate-800/80 bg-white/95 dark:bg-slate-900/95 backdrop-blur flex items-center justify-between shrink-0 z-10"><div><h1 className="text-xl md:text-2xl font-black tracking-tight text-slate-900 dark:text-white">Qrup və İstifadəçilər</h1><p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">Departament və layihə işçi qruplarının idarə edilməsi</p></div><div className="flex items-center gap-2.5"><button onClick={onBulk} className="px-3.5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold shadow transition flex items-center gap-1.5"><svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z" /></svg>Qrup halında istifadəçi əlavə et</button><button onClick={onNewUser} className="px-3.5 py-2 rounded-xl bg-brand-600 hover:bg-brand-700 text-white text-xs font-bold shadow transition flex items-center gap-1.5"><Icon name="plus" />Yeni İstifadəçi</button></div></header>
    <div className="flex-1 overflow-y-auto p-4 md:p-8 space-y-6"><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{groups.map(group => <div key={group.id} className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-sm space-y-4 hover:shadow-md transition">
      <div className="flex items-center justify-between"><div className={`w-10 h-10 rounded-2xl bg-gradient-to-tr ${group.color} flex items-center justify-center text-white font-bold shadow-md`}>{group.name.charAt(0)}</div><span className="px-2.5 py-1 rounded-full text-xs font-bold bg-brand-50 text-brand-700 dark:bg-brand-950 dark:text-brand-300 border border-brand-200">{group.members.length} iştirakçı</span></div>
      <div><h3 className="text-base font-bold text-slate-900 dark:text-white">{group.name}</h3><p className="text-xs text-slate-500 mt-1">{group.description}</p></div>
      <div className="space-y-1.5 pt-2 border-t border-slate-100 dark:border-slate-800"><label className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">İştirakçılar</label><div className="space-y-1 max-h-36 overflow-y-auto pr-1">{group.members.map(member => <div key={member} className="flex items-center justify-between p-2 rounded-xl bg-slate-50 dark:bg-slate-800/60 text-xs"><span className="font-medium text-slate-700 dark:text-slate-200">{member}</span><span className="w-2 h-2 rounded-full bg-emerald-500" /></div>)}</div></div>
      <div className="pt-2 flex items-center gap-2"><button onClick={onChat} className="flex-1 py-2 text-center rounded-xl bg-brand-50 hover:bg-brand-100 dark:bg-brand-950/60 dark:hover:bg-brand-900/60 text-brand-700 dark:text-brand-300 font-bold text-xs transition">Qrup Söhbətinə Keç</button></div>
    </div>)}</div></div>
  </section>;
}
