import Icon from '../common/Icons.jsx';
import { taskStatuses, statusLabel, statusDots } from '../../utils/helpers.js';

export default function TaskDetailModal({ task, onClose, onStatus, onCycle, onDelete }) {
  const selected = task.status === 'Tamamlandı' ? 'Bitmiş' : task.status;
<  return <div role="dialog" aria-modal="true" aria-label="Tapşırıq detalları" className="fixed inset-0 z-50 flex bg-slate-900/60 backdrop-blur-sm items-center justify-center p-4"><div className="bg-white dark:bg-slate-900 rounded-3xl max-w-md w-full p-6 shadow-2xl border border-slate-100 dark:border-slate-800 animate-modal space-y-4">
    <div className="flex items-center justify-between pb-3 border-b border-slate-100 dark:border-slate-800"><div className="flex items-center gap-2"><span className="font-mono text-xs font-bold px-2 py-0.5 rounded-md bg-slate-100 dark:bg-slate-800 text-slate-500">#{task.id}</span><h3 className="text-base font-bold text-slate-900 dark:text-white">{task.title}</h3></div><button onClick={onClose} title="Bağla" className="text-slate-400 hover:text-slate-600"><Icon name="close" className="w-5 h-5" /></button></div>
    <div className="space-y-3 text-xs"><div><label className="text-slate-400">Mesaj / Təsvir:</label><p className="text-slate-800 dark:text-slate-200 mt-0.5 p-3 rounded-xl bg-slate-50 dark:bg-slate-800/60 font-medium">{task.message || '-'}</p></div>
      <div className="grid grid-cols-2 gap-3"><div><label className="text-slate-400">Təyin Edən:</label><p className="font-semibold text-slate-800 dark:text-slate-200">{task.creator}</p></div><div><label className="text-slate-400">İcraçı:</label><p className="font-semibold text-slate-800 dark:text-slate-200">{task.assignee}</p></div></div>
      <div className="grid grid-cols-2 gap-3"><div><label className="text-slate-400">Yaradılma:</label><p className="font-mono text-slate-600 dark:text-slate-400">{task.createdAt}</p></div><div><label className="text-slate-400">Dedlayn:</label><p className="font-mono font-bold text-rose-600">{task.deadline}</p></div></div>
      <div><label className="text-slate-500 dark:text-slate-400 block mb-1.5 font-bold text-[11px] uppercase tracking-wider">Status Variantları (Sürüşdürməli Seçim):</label><div className="grid grid-cols-3 gap-1.5 p-1.5 bg-slate-100 dark:bg-slate-800 rounded-2xl border border-slate-200/80 dark:border-slate-700 text-xs font-semibold">{taskStatuses.map(status => <button key={status} type="button" onClick={() => onStatus(task.id, status)} className={`py-2 px-2 rounded-xl transition flex items-center justify-center gap-1 ${selected === status ? 'bg-white dark:bg-slate-700 text-brand-600 dark:text-brand-300 shadow-sm border border-brand-200 dark:border-brand-600' : 'text-slate-500 dark:text-slate-400 hover:bg-white/60 dark:hover:bg-slate-700/60'}`}><span className={`w-1.5 h-1.5 rounded-full ${statusDots[status]}`} />{statusLabel(status)}</button>)}</div></div>
    </div>
    <div className="flex items-center justify-between pt-3 border-t border-slate-100 dark:border-slate-800"><div className="flex items-center gap-2"><button onClick={() => onCycle(task.id)} className="px-3.5 py-2 text-xs font-bold rounded-xl bg-brand-50 text-brand-700 dark:bg-brand-950 dark:text-brand-300 border border-brand-200">Statusu Dəyiş</button><button onClick={() => onDelete(task.id)} className="px-3 py-2 text-xs font-semibold text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-950/40 rounded-xl">Sil</button></div><button onClick={onClose} className="px-4 py-2 text-xs font-bold text-white bg-slate-800 hover:bg-slate-700 dark:bg-slate-700 rounded-xl">Bağla</button></div>
  </div></div>;
}>
